theme: jekyll-theme-minimal
title: The personal webpage of Maya Lassiter.
description: Current Work, Previous Work, Resume
# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://mayalassiter.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/website"

path: "images/blue.png"
values:
   image: true
   
path: "images/probe.png"
values:
   image: true
   

path: "images/epoxy.png"
values:
   image: true

path: "resume.pdf"
values:
   image: true
path: "ruby.jpg"
values:
   image: true
   
path: "nextman.pdf"
values:
   image: true
path: "mems_report.pdf"
values:
   image: true
