theme: jekyll-theme-minimal
title: The personal webpage of Maya Lassiter.
description: Current Work, Previous Work, Resume

path: "images/blue.png"
values:
   image: true
   
path: "images/probe.png"
values:
   image: true
   

path: "images/epoxy.png"
values:
   image: true

path: "resume.pdf"
values:
   image: true
path: "ruby.jpg"
values:
   image: true
   
path: "nextman.pdf"
values:
   image: true
path: "mems_report.pdf"
values:
   image: true
