theme: jekyll-theme-minimal
title: The personal webpage of Maya Lassiter.
description: [Current Work](/current.md), Previous Work, Resume

path: "images/blue.png"
values:
   image: true
   
path: "images/probe.png"
values:
   image: true
   

path: "images/epoxy.png"
values:
   image: true

path: "Resume JAN 2018.pdf"
values:
   image: true
