theme: jekyll-theme-minimal

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

      path: "images/blue.png"
    values:
      image: true
